version: "3.8"

services:
  db:
    image: postgres:12
    container_name: quotes-db
    environment:
      POSTGRES_USER: quotes-user
      POSTGRES_PASSWORD: quotes-pass
      POSTGRES_DB: quotes-db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: